# Stage 1: Build Next.js
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve dengan Nginx
FROM nginx:stable-alpine
# Salin hasil build statik (folder 'out') ke Nginx
COPY --from=builder /app/out /usr/share/nginx/html
# Masukkan konfigurasi Nginx kita
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]