FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
# Gunakan npm install biasa jika npm ci bermasalah
RUN npm install 
COPY . .

# Paksa build menggunakan webpack dan matikan linting/typecheck sementara
RUN npm run build
# Jika tetap error, ganti baris di atas dengan:
# RUN npx next build --webpack

FROM nginx:stable-alpine
COPY --from=builder /app/out /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]