server {
    listen 3000;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Menambahkan $uri.html agar file login.html bisa diakses via /login
        try_files $uri $uri.html $uri/ /index.html;
    }

    # Proxy untuk API ke Backend Golang
    location /api/ {
        # Hapus slash di ujung IP:Port
        proxy_pass http://10.20.2.77:4000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}