server {
    listen 3000;
    client_max_body_size 50M;

    # Layanan Frontend (Next.js)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri.html $uri/ /index.html;
    }

    # Proxy untuk API Backend
    location /api/ {
        proxy_pass http://10.20.2.77:4000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Akses untuk melihat foto yang sudah diupload
    location /uploads/ {
        proxy_pass http://10.20.2.77:4000/uploads/;
        proxy_set_header Host $host;
    }
}