server {
    listen 3000;
    
    # Supaya bisa upload foto laporan (max 20MB)
    client_max_body_size 20M;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Menghilangkan 403 Forbidden pada route seperti /login
        try_files $uri $uri.html $uri/ /index.html;
    }

    location /api/ {
        # Mengarah ke IP Internal Backend
        proxy_pass http://10.20.2.77:4000; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Timeout agar tidak Bad Gateway saat upload file
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}