name: CI/CD Deployment

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backenddifie:latest ./backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontenddifie:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/backenddifie:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/frontenddifie:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 98.80.187.179
          username: ubuntu
          key: ${{ secrets.EC2_PEM_KEY }}
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            
            # --- BACKEND ---
            docker pull ${{ secrets.DOCKER_USERNAME }}/backenddifie:latest
            docker stop be-server || true && docker rm be-server || true
            
            docker run -d --name be-server \
              -p 4000:4000 \
              -e PORT=4000 \
              -e DB_HOST=dbdifie.cgxgc8wsgidd.us-east-1.rds.amazonaws.com \
              -e DB_PORT=3306 \
              -e DB_USER=admin \
              -e DB_PASS="${{ secrets.DB_PASSWORD }}" \
              -e DB_NAME=reportkecelakaan \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              -e AWS_REGION="us-east-1" \
              -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
              -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
              -e AWS_S3_BUCKET_NAME="${{ secrets.AWS_S3_BUCKET_NAME }}" \
              -e CORS_ALLOWED_ORIGINS="http://98.80.187.179:3000,http://localhost:3000" \
              --restart always ${{ secrets.DOCKER_USERNAME }}/backenddifie:latest

            # --- FRONTEND ---
            docker pull ${{ secrets.DOCKER_USERNAME }}/frontenddifie:latest
            docker stop fe-server || true && docker rm fe-server || true
            docker run -d --name fe-server -p 3000:3000 --restart always ${{ secrets.DOCKER_USERNAME }}/frontenddifie:latest